# Generated by Django 2.1.15 on 2020-04-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourpaws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfiles',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='file_name',
            field=models.CharField(max_length=50),
        ),
    ]
