# Generated by Django 2.1.15 on 2020-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourpaws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilmentddView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('import_file_id', models.CharField(blank=True, max_length=50, null=True)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('charity_urn', models.IntegerField(blank=True, null=True)),
                ('donor_charity_urn', models.CharField(blank=True, max_length=15, null=True)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(blank=True, max_length=20, null=True)),
                ('forename', models.CharField(blank=True, max_length=20, null=True)),
                ('initials', models.CharField(blank=True, max_length=5, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('address3', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.CharField(blank=True, max_length=254, null=True)),
                ('gift_aid', models.CharField(blank=True, max_length=2, null=True)),
                ('source_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fund_code', models.CharField(blank=True, max_length=10, null=True)),
                ('fund_title', models.CharField(blank=True, max_length=10, null=True)),
                ('email_comms_pref', models.CharField(blank=True, max_length=2, null=True)),
                ('mail_comms_pref', models.CharField(blank=True, max_length=2, null=True)),
                ('telephone_comms_pref', models.CharField(blank=True, max_length=2, null=True)),
                ('sms_comms_pref', models.CharField(blank=True, max_length=2, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frequency', models.CharField(blank=True, max_length=10, null=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('card_holders_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_number', models.IntegerField(blank=True, null=True)),
                ('bank_sort_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fulfilmentdd_view',
                'managed': False,
            },
        ),
    ]
